ACPO inline model train bug fix
Huawei-CPLLab/ACPO pull request #5
Opened 2024-10-15 11:04 UTC by wangzm509

1.Bypass some environment errors.
2.Fix some train errors.
3.Avoid the problem that the loss function doesn't match the task.
4.Provide .csv and config in table test for training inline model.
Now we can use config and csv(in table test) to train inline model.
cmd:
1.cd ACPO-model/src
2.python train.py --root-path . --user-config ../test/config/user_train_config.json --data-dir ./data --save-model --epochs 1 --task classification --algorithm nn --cv kfold --folds 2 --loss cross_entropy

2024-10-17 01:58 UTC, tejas-srikanth approved these changes
Changes look good to me. Might still want to wait for Tom and Amir's input though

2024-10-17 13:27 UTC, tsczajkowski commented
Can you squash commits under your name into one? Most of the changes are related to the same topic, so perhaps keeping the commits separate is not as convenient.

2024-10-18 01:49 UTC, wangzm509 commented
> Can you squash commits under your name into one? Most of the changes are related to the same topic, so perhaps keeping the commits separate is not as convenient.

okey i will do that

2024-10-18 18:19 UTC, tsczajkowski requested changes

2024-10-18 18:19 UTC, tsczajkowski commented on ACPO-model/src/utils.py
> +    tensorflow stopped addon support a while ago,we are finding solution now
Space after ,

2024-10-21 01:49 UTC, wangzm509 commented on ACPO-model/src/utils.py
> +    tensorflow stopped addon support a while ago,we are finding solution now
done

2024-10-21 01:49 UTC, wangzm509 commented on ACPO-model/src/losses.py
> +    assert exists_zero == False, "ERR:There are 0 in the target,can't use mae_norm loss"
done

2024-10-21 01:49 UTC, wangzm509 commented on ACPO-model/src/losses.py
> +    assert exists_zero == False, "ERR:There are 0 in the target,can't use mse_norm loss"
done

2024-10-21 14:39 UTC, tsczajkowski approved these changes

2024-10-21 14:39 UTC, merged